### ISSUE TITLE
Configuring namespace

### ISSUE THREAD

**Issue by dyeshurun** [stitchfix/resque-brain#65]
Is it possible to use redis namespace other then the default resque namespace? We have a single resque server and use different namespace to differ between "domains".

**Comment by davetron5000** [comment]
[this](https://github.com/stitchfix/resque-brain/blob/1ec7fac9ded3de5b67c44f434f36f2244262baf9/app/models/resques.rb#L12) is the place where the redises get configured and it's used [here](https://github.com/stitchfix/resque-brain/blob/1ec7fac9ded3de5b67c44f434f36f2244262baf9/config/initializers/resque_instances.rb#L10).

One thing you could do is modify the `from_environment` method so that it checks for additional env vars that could contain the namespace, e.g.:

```ruby
namespace = ENV['RESQUE_BRAIN_#{instance_name}_namespace'] || "resque"
```

I guess you could also use a custom URL format and parse it out of there as well:

```ruby
# From https://github.com/stitchfix/resque-brain/blob/1ec7fac9ded3de5b67c44f434f36f2244262baf9/app/models/resque_url.rb

class ResqueUrl
  attr_reader :url, :namespace

  def initialize(resque_name)
    @resque_name = resque_name
  end

  def parse_url
    @url = environment_variables.map { |environment_variable|
      ENV[environment_variable]
    }.compact.first
    if @url.nil?
      raise MissingResqueConfigurationError.new(environment_variables,@resque_name)
    end
    # super cheesy
    @namespace = @url.gsub(/^.*namespace=/,'')
    @url = @url.gsub(/namespace=.*$/,'')
  end

  private

  def environment_variables
    [
      "RESQUE_BRAIN_INSTANCES_#{@resque_name}", 
      "#{@resque_name.gsub(/-/,'_').upcase}_RESQUE_REDIS_URL",
    ]
  end
end
```

**Comment by jeremywadsack** [comment]
It looks like this issue can be closed now.
